modLoader="javafml"
loaderVersion="[36,)"
license="GPL-2.0"
[[mods]]
modId="simplespawn"
version="1.0.0"
displayName="Simple Spawn"
authors="Clairton Santos (ItsClairton)"
description="Just a simple /spawn mod"